### ISSUE TITLE
Sort results so they are consistent

### ISSUE THREAD

**Issue by jsirianni** [jsirianni/gocron-frontend#3]
When refreshing the page, results change position. Perhaps `SORT BY account` would fix this?

**Comment by JarrodMFlesch** [comment]
Going to use 'ORDER BY $account'

**Comment by jsirianni** [comment]
Resolved in commit: https://github.com/jsirianni/gocron-frontend/pull/5/commits/e7914b6525e96c58584980806c7314188aabf2f8
